# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-05 20:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_auto_20181005_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='message',
            field=models.TextField(default='default_message', verbose_name='Message'),
            preserve_default=False,
        ),
    ]
