# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-10 16:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_contactcaptchaformfield_hide_label'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='first_names',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='last_names',
        ),
        migrations.RemoveField(
            model_name='contactcaptchaformfield',
            name='hide_label',
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='subject',
            field=models.CharField(default='', max_length=254, verbose_name='Subject'),
            preserve_default=False,
        ),
    ]
