# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-13 15:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpage',
            old_name='tags_en',
            new_name='tags',
        ),
    ]
