# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-02 17:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('blog', '0002_auto_20181002_1642'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogTagIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AlterField(
            model_name='blogpagetages',
            name='content_object',
            field=modelcluster.fields.ParentalKey(help_text='Listado separado por comas de tags', on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items_es', to='blog.BlogPage', verbose_name='tagggggs'),
        ),
    ]
