# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-09 21:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0021_image_file_hash'),
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='peopleindexpage',
            name='image',
            field=models.ForeignKey(blank=True, help_text='Homepage image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
