# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-10 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_peopleindexpage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='captchaformfield',
            name='placeholder',
            field=models.CharField(blank=True, max_length=255, verbose_name='placeholder'),
        ),
    ]
