# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-10 16:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_captchaformfield_hide_label'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='captchaformfield',
            name='hide_label',
        ),
    ]
