# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-10 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_remove_captchaformfield_hide_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='captchaformfield',
            name='additional_attrs',
            field=models.CharField(blank=True, help_text='Comma separated list of key-value pairs to add to the input element. Quotes are not necessary.\ne.g. data-toggle=dropdown,aria-haspopup=true', max_length=254, null=True, verbose_name='additional classes'),
        ),
        migrations.AddField(
            model_name='captchaformfield',
            name='additional_classes',
            field=models.CharField(blank=True, help_text='Comma separated list of html classes to pass on to the input element.', max_length=254, null=True, verbose_name='additional classes'),
        ),
        migrations.AlterField(
            model_name='captchaformfield',
            name='placeholder',
            field=models.CharField(blank=True, help_text='Placeholder text. This takes precedence over a placeholder set in additional_attrs.', max_length=254, verbose_name='placeholder'),
        ),
        migrations.AlterField(
            model_name='captchaformfield',
            name='placeholder_en',
            field=models.CharField(blank=True, help_text='Placeholder text. This takes precedence over a placeholder set in additional_attrs.', max_length=254, null=True, verbose_name='placeholder'),
        ),
        migrations.AlterField(
            model_name='captchaformfield',
            name='placeholder_es',
            field=models.CharField(blank=True, help_text='Placeholder text. This takes precedence over a placeholder set in additional_attrs.', max_length=254, null=True, verbose_name='placeholder'),
        ),
    ]
