# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-10 20:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_auto_20181010_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='captchaformfield',
            name='additional_attrs',
            field=models.CharField(blank=True, help_text='Comma separated list of key-value pairs to add to the input element. Quotes are not necessary.\ne.g. data-toggle=dropdown,aria-haspopup=true', max_length=254, null=True, verbose_name='additional attributes'),
        ),
    ]
