# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-12 13:43
from __future__ import unicode_literals

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_auto_20181010_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standardpage',
            name='introduction',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='Text to describe the page'),
        ),
        migrations.AlterField(
            model_name='standardpage',
            name='introduction_en',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='Text to describe the page', null=True),
        ),
        migrations.AlterField(
            model_name='standardpage',
            name='introduction_es',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='Text to describe the page', null=True),
        ),
    ]
