# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-13 15:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_auto_20181012_1343'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='image',
            new_name='hero_image',
        ),
    ]
