# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-13 23:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_homepagefeaturerelationship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagefeaturerelationship',
            name='feature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_home_relationship', to='base.StandardPage'),
        ),
    ]
