# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-14 00:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('base', '0013_auto_20181013_2359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='featured_section_1',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='featured_section_1_title',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='featured_section_1_title_en',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='featured_section_1_title_es',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='featured_section_2',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='featured_section_2_title',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='featured_section_2_title_en',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='featured_section_2_title_es',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='featured_section_3',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='featured_section_3_title',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='featured_section_3_title_en',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='featured_section_3_title_es',
        ),
        migrations.RemoveField(
            model_name='homepagefeaturerelationship',
            name='feature',
        ),
        migrations.AddField(
            model_name='homepagefeaturerelationship',
            name='featured_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feature_home_relationship', to='wagtailcore.Page'),
        ),
        migrations.AddField(
            model_name='homepagefeaturerelationship',
            name='title',
            field=models.CharField(blank=True, help_text="Title to display on the Home Page, if left blank, the featured page's title will be used", max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='homepagefeaturerelationship',
            name='title_en',
            field=models.CharField(blank=True, help_text="Title to display on the Home Page, if left blank, the featured page's title will be used", max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='homepagefeaturerelationship',
            name='title_es',
            field=models.CharField(blank=True, help_text="Title to display on the Home Page, if left blank, the featured page's title will be used", max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='homepagefeaturerelationship',
            name='page',
            field=modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_feature_relationship', to='base.HomePage'),
        ),
    ]
