# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-14 11:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers
import wagtail.core.models
import wagtail.search.index


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('taggit', '0002_auto_20150616_2121'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0018_auto_20181014_0111'),
    ]

    operations = [
        migrations.CreateModel(
            name='StyleDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('file', models.FileField(upload_to='documents', verbose_name='file')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('file_size', models.PositiveIntegerField(editable=False, null=True)),
                ('collection', models.ForeignKey(default=wagtail.core.models.get_root_collection_id, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailcore.Collection', verbose_name='collection')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text=None, through='taggit.TaggedItem', to='taggit.Tag', verbose_name='tags')),
                ('uploaded_by_user', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='uploaded by user')),
            ],
            options={
                'verbose_name': 'document',
                'abstract': False,
            },
            bases=(wagtail.search.index.Indexed, models.Model),
        ),
        migrations.AddField(
            model_name='homepagefeaturerelationship',
            name='slug',
            field=models.SlugField(default='', help_text="Slug to refer to the feature page when calling it through the 'featured_page_single' template tag. Required.", max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='homepagefeaturerelationship',
            name='style',
            field=models.ForeignKey(blank=True, help_text="Style snippet to use, will use a default style if left blank. Take a look at the default file in 'base/static/scss/default-snippets/default.scss and other files there for some examples on how to setup the [S]CSS classes.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='base.StyleSnippet'),
        ),
        migrations.AlterField(
            model_name='stylesnippet',
            name='class_name',
            field=models.SlugField(help_text='Name of the CSS class name that the snippet willbe rendered with. Be careful not to choose a class name that will interfere with the rest of the styles. The same class name needs to match the class defined in the style_file.', max_length=254, verbose_name='class name'),
        ),
        migrations.AlterField(
            model_name='stylesnippet',
            name='style_file',
            field=models.ForeignKey(help_text='Only filenames ending in .css, .scss or .sass will be processed.', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='base.StyleDocument', verbose_name='style file'),
        ),
    ]
