# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-14 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_auto_20181014_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='styledocument',
            name='source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
